name: build

on: 
  push:
    branches:
      - autobuild_setup

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps  :
      - name : test print
        run  : echo "this is test print"
        shell: bash